=== VowpalWabbit/vowpal_wabbit/test/vwtest.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "http://vowpalwabbit.org/schemas/runtests.schema.json",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "number"
            },
            "desc": {
                "type": "string"
            },
            "vw_command": {
                "type": "string"
            },
            "bash_command": {
                "type": "string"
            },
            "diff_files": {
                "type": "object",
                "patternProperties": {
                    "^.*$": {
                        "type": "string"
                    }
                }
            },
            "input_files": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "depends_on": {
                "type": "array",
                "items": {
                    "type": "number"
                }
            }
        },
        "required": [
            "id"
        ],
        "oneOf": [
            {
                "required": [
                    "vw_command"
                ]
            },
            {
                "required": [
                    "bash_command"
                ]
            }
        ],
        "additionalProperties": false
    }
}

=== VowpalWabbit/vowpal_wabbit/test/privacy_activation.vwtest.json
[
    {
        "id": 1,
        "desc": "test privacy_activation command line argument",
        "vw_command": "--privacy_activation -d train-sets/privacy_dataset --invert_hash readable_model_privacy.txt --cbify 2 --cb_adf --predict_only_model --log_output compat",
        "diff_files": {
            "stderr": "train-sets/ref/privacy_dataset.stderr",
            "readable_model_privacy.txt": "pred-sets/ref/readable_model_privacy.txt"
        },
        "input_files": [
            "train-sets/privacy_dataset"
        ]
    },
    {
        "id": 2,
        "desc": "test privacy_activation command line argument with no tags input",
        "vw_command": "--privacy_activation -d train-sets/privacy_dataset_no_tags --invert_hash readable_model_privacy_no_tags.txt --cbify 2 --cb_adf --predict_only_model --log_output compat",
        "diff_files": {
            "stderr": "train-sets/ref/privacy_no_tags.stderr",
            "readable_model_privacy_no_tags.txt": "pred-sets/ref/readable_model_privacy_no_tags.txt"
        },
        "input_files": [
            "train-sets/privacy_dataset_no_tags"
        ]
    }
]

=== VowpalWabbit/vowpal_wabbit/test/slow.vwtest.json
[
  {
    "id": 1,
    "desc": "save_resume_test",
    "bash_command": "python3 save_resume_test.py --filename train-sets/rcv1_small.dat --verbose_on_fail --vw {VW}",
    "input_files": [
      "train-sets/rcv1_small.dat"
    ]
  },
  {
    "id": 2,
    "desc": "test_race_condition",
    "bash_command": "python3 repeat.py 1024 {VW} train-sets/rcv1_small.dat --holdout_after 100",
    "input_files": [
      "train-sets/rcv1_small.dat"
    ]
  }
]
